FROM mambaorg/micromamba:1.5.6

# This dockerfile uses cached mounts, so to build use e.g.
# $ DOCKER_BUILDKIT=1 docker build .

WORKDIR /lorikeet

# Install man-db. We cannot use conda because man-db doesn't appear to be
# available in any conda repo
USER root
RUN apt update && apt install -y man-db
USER $MAMBA_USER

# Install lorikeet
RUN --mount=type=cache,target=/opt/conda/pkgs micromamba install -n base -c conda-forge -c bioconda -c defaults lorikeet-genome==LORIKEET_VERSION

# ADD lorikeet.yml /lorikeet.yml
# RUN --mount=type=cache,target=/opt/conda/pkgs micromamba install -c conda-forge -c bioconda -c defaults -n base git -f /lorikeet.yml
# RUN --mount=type=cache,target=/opt/conda/pkgs micromamba clean --all --yes

# This is needed to activate the environment in the dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1

# RUN git clone https://github.com/rhysnewell/Lorikeet . && git checkout vLORIKEET_VERSION

# # isntall rust
# USER root
# RUN apt-get install -y curl
# USER $MAMBA_USER
# RUN curl -sSf https://sh.rustup.rs | sh -s -- -y
# ENV PATH="/home/mambauser/.cargo/bin:${PATH}"
# USER root
# RUN apt-get install -y build-essential
# USER $MAMBA_USER
# RUN cargo install --path .

# # Remove extraneous files
# # RUN rm -rfv *

# # Run some tests
# USER root
# RUN apt-get install -y python3
# USER $MAMBA_USER
# RUN ls /lib/x86_64-linux-gnu/libpytho* && lorikeet --version
RUN lorikeet call --full-help



# Remove all the build dependencies / image layers for a smaller image overall
FROM scratch
COPY --from=0 / /

## The following is to add micromamba back into the image, from https://micromamba-docker.readthedocs.io/en/latest/advanced_usage.html#adding-micromamba-to-an-existing-docker-image

# # bring in the micromamba image so we can copy files from it
# FROM mambaorg/micromamba:1.5.6 as micromamba

# # This is the image we are going add micromaba to:
# FROM tomcat:9-jdk17-temurin-focal

USER root

# if your image defaults to a non-root user, then you may want to make the
# next 3 ARG commands match the values in your image. You can get the values
# by running: docker run --rm -it my/image id -a
ARG MAMBA_USER=mambauser
ARG MAMBA_USER_ID=57439
ARG MAMBA_USER_GID=57439
## Make the default user root because otherwise there are permission issues in google batch
# ARG MAMBA_USER=root
# ARG MAMBA_USER_ID=0
# ARG MAMBA_USER_GID=0
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

# ## These below are not necessary because the copy from the micromamba image already has them, and doing it just adds to the the image size.
# COPY --from=micromamba "$MAMBA_EXE" "$MAMBA_EXE"
# COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
# COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh
# COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh
# COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
# COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh

# RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
#     /usr/local/bin/_dockerfile_setup_root_prefix.sh

USER $MAMBA_USER

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

WORKDIR /
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh","lorikeet"]
